baseURL: "/"
title: Naveed D. Riaziat
# pagination.pagerSize: 60
theme: ["PaperModAcademic", "hugo-shortcode-gallery"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: G-R2M9JEHJLQ

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Naveed D. Riaziat
  description: "PhD Student at Johns Hopkins University"
  keywords: ["medical robotics", "haptic feedback", "algorithms"]
  author: Me
  images: ["images/profile.jpg"]
  defaultTheme: light
  disableThemeToggle: false

  ShowOnlySelectedPubs: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text:
    icon: /apple-touch-icon.png
    iconHeight: 

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set

  # home-info mode
  homeInfoParams:
    Title: Naveed D. Riaziat
    Content: |
        I am a PhD Candidate studying under Prof. Jeremy D. Brown in the [Haptics and Medical Robotics Lab](https://hamr.lcsr.jhu.edu) at Johns Hopkins University. 
        Previously, I finished my BS in Mechanical Engineering at Purdue University and my MS in Robotics at Johns Hopkins University.
        My research focuses on advancing medical robotics technology, specifically with regards to surgeon-in-the-loop control, novel sensing methods, and haptic interfaces. 
        On occasion, I also fret about my espresso routine, take photos, and make pottery.\
        \
        Download my [CV](/files/Academic_CV-redacted.pdf).
    imageUrl: "images/profile.jpg"
    imageTitle: profile
    imageWidth: 240
    imageHeight: 240
  
  socialIcons:
    # - name: email
    #   url: "mailto:hlee307[at]ucmerced.edu"
    - name: github
      url: "https://github.com/nriaziat"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=IM1ku7MAAAAJ"
    - name: linkedin
      url: "https://www.linkedin.com/in/nriaziat"

  # analytics:
  #   google:
  #     SiteVerificationTag: -1-9r4oo9sAFcKiCWEg8koj3qpJdLUOO3-2L_E0jYqs

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Publications
      url: pubs
      weight: 10
    - name: Pottery
      url: pottery
      weight: 20
    - name: Photography
      url: photography
      weight: 30
    - name: Work Experience 
      url: work
      weight: 40
    # - name: Search 
    #   url: search
    #   weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai